### ISSUE TITLE
Co-locate stories with components.

### ISSUE THREAD

**Issue by philcockfield** [kadirahq/react-native-storybook#103]
Is there an equivalent way to find stories that sit alongside their components with a `.stories` extension like you can on web:

```
const req = require.context('../lib/view', true, /.stories.js$/);
configure(() => {
  req.keys().forEach(filename => req(filename));
}, module);
```

(ref: https://getstorybook.io/docs/basics/writing-stories)

**Comment by thani-sh** [comment]
React Storybook uses `require.context` to do that which is a Webpack feature. So far, we don't know of any equivalent feature in React Native bundler. I'll see what we can do to enable this.

**Comment by philcockfield** [comment]
That would be awesome if it's in any way possible!! - thanks @mnmtanish

**Comment by ckothari** [comment]
+1

**Comment by skovhus** [comment]
Semi automated way here https://github.com/elderfo/react-native-storybook-loader

But would be great to avoid the build step.

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
