### ISSUE TITLE
Android "websocket: connection error", "Failed to connect to localhost/127.0.0.1:7007"

### ISSUE THREAD

**Issue by tracyxiong1** [kadirahq/react-native-storybook#107]
Hi, there was an error on the Android platform, working on the iOS.
Error message is " websocket: connection error", "Failed to connect to localhost/127.0.0.1:7007".

```
npm i -g getstorybook
cd my-react-app
getstorybook
```
react-native 0.31.0
getstorybook 1.6.1

**Comment by thani-sh** [comment]
Can you try forwarding that port

``` shell
adb reverse tcp:7007 tcp:7007
```

**Comment by tracyxiong1** [comment]
@mnmtanish Cool! It looks like it's going to work, but why do I have to do it? Is this a bug of Android?

**Comment by thani-sh** [comment]
It happens because `localhost` in the android device does not point to the host machine. This command will tunnel data from Android device to host machine for that port. The iOS simulator does this automatically

**Comment by Kishanjvaghela** [comment]
@mnmtanish adb reverse was introduced in Android 5.0
