### ISSUE TITLE
Add a suite of tests to check with new versions of React Native

### ISSUE THREAD

**Issue by thani-sh** [kadirahq/react-native-storybook#108]
React Native gets updated quite often, as we're not using any internal APIs now React Native Storybook should work without an issue. It'll be good to have a suite of test to verify that. It'll be great if it can be completely automatic but it's not a must.

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
