### ISSUE TITLE
Don't work if Debug server host is setted: websocket: connection error", "Failed to connect to localhost/127.0.0.1:7007

### ISSUE THREAD

**Issue by linonetwo** [kadirahq/react-native-storybook#116]
I use wifi to sent bundle, in Dev settings, I set Debug server host to 10.0.0.90:8081, and bundle was sent. But socket seems still try to connecting 127.0.0.1:7007.

I think socket should read Dev setting, and try to connect 10.0.0.90:7007 if I have set it.

Seems running "storybook start -h 10.0.0.90 -p 7007" can't help.

**Comment by linonetwo** [comment]
Ok, seems using:

```javascript
const StorybookUI = getStorybookUI({port: 7007, host: '10.0.0.90'});
```
can do this.

**Comment by linonetwo** [comment]
But I think it's better to read Dev settings...Since this is config, prefer not hardcoded.

**Comment by linonetwo** [comment]
Well, after searching. I still don't know how to read Dev settings, or I could have made a PR...

Tell me if anybody know the way to do this.

**Comment by thani-sh** [comment]
Hi @linonetwo

Thanks for opening the issue. If you find a way to pass some config info into the React Native app at build time without hard coding it, please let me know. So far, the only I way I found is by dynamically generating a JS file when starting storybook and importing it into the RN app. I'm trying to find a better way to do this.

**Comment by DandroidDeveloper** [comment]
In Android Studio on Ubuntu localhost needs to be changed to 10.0.2.2 in order for storybook to work, the emulator doesn't recognize localhost

**Comment by linonetwo** [comment]
Nowadays I just read different config files when running by different npm script....

**Comment by gourav-singhal** [comment]
Hi

I am getting this same error I tried the solution as suggested by @linonetwo but still no success. Can anybody help ?

**Comment by tutaslabs** [comment]
adb reverse tcp:7007 tcp:7007

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
