### ISSUE TITLE
Possible to use storybook-addon-knobs?

### ISSUE THREAD

**Issue by hadfieldn** [kadirahq/react-native-storybook#117]
I get an error when [importing](https://github.com/storybooks/storybook-addon-knobs#getting-started) `@kadira/storybook-addon-knobs/register` due to a [dependency on insert-css](https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/types/Date/index.js#L20), which [requires](https://github.com/substack/insert-css/blob/master/index.js#L14) `document`.

Is there another way to register addons with react-native-storybook so that they're registered for the browser rather than the device?

**Comment by arunoda** [comment]
Let's discuss here - https://github.com/storybooks/storybook-addon-knobs/issues/83
