### ISSUE TITLE
Use .babelrc of parent directory Instead of storybook

### ISSUE THREAD

**Issue by linonetwo** [kadirahq/react-native-storybook#119]
Seems RNStorybook will not use .babelrc that RN will use when normally started. Is that true?  
I found this because I can't use @decorator when using RNStorybook.

**Comment by f0rr0** [comment]
This also throws with `ex-navigation` which uses decorators

**Comment by ritz078** [comment]
@mnmtanish any guide about how can we use custom `.babelrc` for this ? As there's no .storybook folder here I guess maybe there's something else ?

**Comment by thani-sh** [comment]
Released `v2.2.2` with a fix. Now it'll look for custom .babelrc files in both `project/storybook` directory and `project` directory in that order.

**Comment by stevenyap** [comment]
I am using `v2.2.4` and it does not look for my .babelrc in my project directory.
Copying a copy of .babelrc in the `storybook` directory works though.
