### ISSUE TITLE
Support RN 0.43.x

### ISSUE THREAD

**Issue by xareelee** [kadirahq/react-native-storybook#135]
After installing RN `0.43.x`, I got those warning using `yarn install`:

```
warning "@kadira/react-native-storybook@2.3.0" has incorrect peer dependency "react@^15.3.2".
warning "@kadira/react-native-storybook@2.3.0" has incorrect peer dependency "react-native@0.27.0 - 0.42.x".
```

RN `0.43.x` depends on react `16.0.0-alpha.6`. Is it possible to make react-native-storybook support RN `0.43x` and react `16.0.0-alpha.6`?

**Comment by MoOx** [comment]
Curious to know what is the effort here. How can we help?

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
