### ISSUE TITLE
It's fail to Installing dependencies

### ISSUE THREAD

**Issue by duanyachao** [kadirahq/react-native-storybook#136]
i quick start  storybook from npm i -g getstorybook  & getstorybook .but it's fail  at the second step "Installing dependencies  ". can anyone help?
![qq 20170520180337](https://cloud.githubusercontent.com/assets/7410447/26274880/fe7677a2-3d86-11e7-87df-2ae709132e0e.png)

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
