### ISSUE TITLE
404 Link on Readme "Setup React Native Storybook with Android"

### ISSUE THREAD

**Issue by geirman** [kadirahq/react-native-storybook#29]
The link to "Setup React Native Storybook with Android" on the readme is broke and points to https://github.com/kadirahq/react-native-storybook/blob/master/docs/setup-android.md

**Comment by thani-sh** [comment]
The link is no longer broken. But the Android guide is not ready yet so the doc is empty. We'll fix it as soon as we figure out a good way to do it.

Thanks for the issue.

**Comment by thani-sh** [comment]
@geirman the Android guide is ready :)
I'll close this issue.
