### ISSUE TITLE
Only works when "Remote JS Debug" is on

### ISSUE THREAD

**Issue by thani-sh** [kadirahq/react-native-storybook#3]
The websocket connection only works when the "Remote JS Debug" is on and the debugger tab is also available. Find out why and fix it.

**Comment by arunoda** [comment]
We don't need websockets. Use socket.io. It'll use XHR if websocket is not available. We should not need to worry on these stuff.

**Comment by thani-sh** [comment]
Already using socket.io. It's quite buggy btw, had to use a patched version to get it to work. This issue is not related to that.

**Comment by arunoda** [comment]
@mnmtanish I added this to the initial release.

**Comment by thani-sh** [comment]
Fixed with https://github.com/kadirahq/react-native-storybook/pull/17
