### ISSUE TITLE
Simplify the starting process

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-native-storybook#33]
Right now, in order to start the storybook we need to run the app normally and start the storybook server separately. 

This gets worst, when it's for Android. 

We need to simplify this and simply use a single npm script to run start the whole process like this:

```
npm run storybook-ios
```

or 

```
npm run storybook-android <device-id>
```

**Comment by thani-sh** [comment]
`run-ios` and `run-android` commands are already there. It will start storybook app on devices but the server needs to be started. Starting the storybook server separately can be useful when we view storybook on multiple devices at the same time.

**Comment by arunoda** [comment]
Got it.
