### ISSUE TITLE
Missing linkTo

### ISSUE THREAD

**Issue by jairtrejo** [kadirahq/react-native-storybook#40]
I believe not all of the API from [this guide to writing stories](https://github.com/kadirahq/react-storybook/blob/master/docs/writing_stories.md) is implemented. Notably, the `linkTo` function is missing.

I am unsure if maybe I'm supposed to import it in a special way, so I filed this issue.

Thank your for this project! Being able to use it for React Native has been awesome.

**Comment by arunoda** [comment]
@mnmtanish any comments on this?

**Comment by thani-sh** [comment]
I'll check it out. I think I can get this ready by tomorrow.

**Comment by thani-sh** [comment]
@jairtrejo linkTo works from `v1.11.2`. Sorry about the delay guys, had to do some code refactoring before adding this feature. Anyways, future code changes will be easier from now.
