### ISSUE TITLE
Use a different app name for storybook

### ISSUE THREAD

**Issue by thani-sh** [kadirahq/react-native-storybook#5]
Storybook uses the same name as the app so it will be replaced in the device/simulator. Use a different name (maybe suffix "Storybook" to the app name) so both the app and storybook can be on the same device at the same time.

**Comment by thani-sh** [comment]
Try to do this when writing the package script if possible https://github.com/kadirahq/react-native-storybook/issues/4

**Comment by arunoda** [comment]
This is a valid point.

**Comment by thani-sh** [comment]
It's ready for iOS. I think @roonyh wrote a guide for the Android as well. We can close this one as soon as we merge the Android guide.

**Comment by thani-sh** [comment]
Fixed with #32
