### ISSUE TITLE
Add an easy way to start using Storybook

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-native-storybook#51]
Currently using storybook is non ideal(replacing index) or non trivial(configuring platform files).
So, we need to create another method which sites in between. Here's my idea:

There's a floating button on the screen where it renders on top of any other component. Just like iPhone's accessibility button.

When the user clicks on that button, it'll toggle the storybook's preview. I think that's a pretty good way to add storybook to any RN project. We could enable this only in the dev mode.

**Comment by rootedsoftware** [comment]
I really like this. Also, could you use some of the quick key combos, like React Native does to switch between these? (I'm thinking of the CMD + R they use).

**Comment by arunoda** [comment]
@c316 We were looking at that too, but the problem is `CMD + R` is a special functionality. Not sure how to get something like that.

Anyway, we can try.

**Comment by arunoda** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;i53FzTM2&#x2F;1-add-getstorybook-support-for-react-native"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add getstorybook support for React Native.</a>

**Comment by arunoda** [comment]
I think this is already implemented now.
Check the README :) 

@mnmtanish nice work.
