### ISSUE TITLE
Cannot install with RN >= 0.30.0

### ISSUE THREAD

**Issue by alloy** [kadirahq/react-native-storybook#54]
The [version requirement you have on RN](https://github.com/kadirahq/react-native-storybook/blob/977f6e86cca5afd57ec502193ee3ba508b30a282/package.json#L29) states that it may not go over 0.27.x, meaning that npm complains when we try to use it with RN 0.30.0 and shrinkwrap.

> Allows changes that do not modify the left-most **non-zero** digit in the [major, minor, patch] tuple.
> – https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

FWIW Your package seems to work fine with RN 0.30.0.

**Comment by thani-sh** [comment]
Hi @alloy 
Released `v1.12.5` which has `0.27.0 - 0.30.x` for react-native peer dependency versions.
I'll check it with `v0.31.0` and do another patch release soon.

**Comment by thani-sh** [comment]
Release `v1.12.6` supports react-native versions upto `v0.31.0`

**Comment by alloy** [comment]
Awesome, thanks for the fast turnaround time! :+1:
