### ISSUE TITLE
Got an error when I access the storybook for the first time.

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-native-storybook#57]
See this error: 
<img width="487" alt="screen shot 2016-08-25 at 10 35 40 pm" src="https://cloud.githubusercontent.com/assets/50838/17978571/59a2e340-6b14-11e6-92a7-e5a58da8c37c.png">
### How to Reproduce
- npm run storybook
- react-native run-ios
- Then there's a blank screen on the phone.
- Now, open storybook at http://localhost:7007

Then you'll get this error.

When I reload the app, this error will be gone. 

> I think this is related to selecting null as the current story or something similar.

**Comment by Malenconiaprincep** [comment]
I met this problem  when i use react-native run-ios 
`ENOENT: no such file or directory, uv_chdir`   how to solve it ?
