### ISSUE TITLE
Application periodic has not been registered

### ISSUE THREAD

**Issue by lorensr** [kadirahq/react-native-storybook#58]
I get the below error screen after doing the following:

``` sh
$ react-native init periodic
$ cd periodic
$ getstorybook
$ npm run storybook
```

```
$ react-native run-ios
```

![image](https://cloud.githubusercontent.com/assets/251288/17992310/23d9f0c8-6b14-11e6-8bd6-7f3b3b0702d5.png)

There are no errors when I do `npm run start`.

```
$ react-native -v
react-native-cli: 1.0.0
react-native: 0.32.0
$ getstorybook --version
1.4.0
```

Repo: https://github.com/lorensr/react-native-periodic

The only warning I got during `getstorybook` was the peer dependency of RN `0.31.0`, whereas `react-native init` used `0.32.0`. Do I need to downgrade?

**Comment by thani-sh** [comment]
We need to make a small edit to the index.ios.js file in storybook dir. We'll push an update for getstorybook to automate this ASAP.

**Comment by lorensr** [comment]
Thanks! Once it's updated, I should do this?

```
npm i -g getstorybook
getstorybook -f
```

**Comment by thani-sh** [comment]
Yes that should work. I've also opened a PR.

**Comment by arunoda** [comment]
@lorensr As for a quick fix, go to storybook/index.ios.js and add **periodic** for `AppRegistry.registerComponent`.

I hope there's something else there.
I mean this like: https://github.com/lorensr/react-native-periodic/blob/master/storybook/index.ios.js#L11

**Comment by lorensr** [comment]
Made the change. Now web UI has stories, and I get a different error:

![image](https://cloud.githubusercontent.com/assets/251288/17994239/c7911812-6b24-11e6-9d36-cd9b7d81b0c0.png)

**Comment by arunoda** [comment]
Reload the app now. Related to #57

**Comment by lorensr** [comment]
Okay now blank:

![image](https://cloud.githubusercontent.com/assets/251288/17995276/622f41ba-6b2e-11e6-8ceb-862e78fefd5a.png)

![image](https://cloud.githubusercontent.com/assets/251288/17995279/67071596-6b2e-11e6-89c3-dbe35a419594.png)

![image](https://cloud.githubusercontent.com/assets/251288/17995295/77ea6fa2-6b2e-11e6-86a3-cf7bf3d94467.png)

**Comment by arunoda** [comment]
Weird. @mnmtanish could you check the above linked repo?

**Comment by thani-sh** [comment]
Just checked it out, and it was working okay.

My guess is that its showing the blank page because the current story is not set (related issue #56). When a RN app starts, the browser should send the active story (through the server) for it to display. This won't happen if the websocket connection between the browser and the server closed for some reasons (opened an issue for this #66).

**Comment by thani-sh** [comment]
- Released `getstorybook v1.4.1` which fixes the issue mentioned [here](https://github.com/kadirahq/react-native-storybook/issues/58#issue-173356684)
- Released `@kadira/react-native-storybook v2.0.1` which fixes the issue mentioned [here](https://github.com/kadirahq/react-native-storybook/issues/58#issuecomment-242628121)

**Comment by lorensr** [comment]
Just tried again. At first, got blank screen, but then hit cmd-R again, and it works!

**Comment by tmaly1980** [comment]
@mnmtanish,  I'm still having issues with getstorybook where it just prints %APP_NAME% into my storybook/index.js . I ran:

 `npm i -g @storybook/cli`

And then `getstorybook,` which sets

`@storybook/react-native: ^3.1.3
`

in my package.json. However, the generated storybook/storybook.js still has %APP_NAME%, even when I wipe out my storybook/storybook.js and call `getstorybook -f` .
