### ISSUE TITLE
Storybook webapp preview area is blank

### ISSUE THREAD

**Issue by thani-sh** [kadirahq/react-native-storybook#63]
The preview area is blank at the moment (as preview is done using simulators).

**Options**
1. add a simple user guide whch asks users to run the simulator
2. make it configurable with the addon api and let users decide
3. make it configurable and then use it to add user guide by default

**Comment by arunoda** [comment]
We can that screenshot preview thing here. It will be pretty useful.

**Comment by thani-sh** [comment]
Addon developers can use the addons API to set whatever they want there. We can include the screenshots addon by default as soon as it's ready.

**Comment by FaridSafi** [comment]
I suggest to allow to render a custom image/text as a preview for each story
Eg: displaying a mockup of the component to develop

Edit: I finally created an [addon](https://github.com/LeReacteur/storybook-addon-mockup) to display a mockup

**Comment by elie222** [comment]
I'm confused how Storybook is supposed to work for RN. I'm running the app on iOS simulator, and have gone to the storybook url in the browser, but i dont see any components. it's just an empty storybook

**Comment by thani-sh** [comment]
Hi @elie222 
We're still working on the preview area. Please start the iOS/Android simulator/emulator to check it out for now. Check this [readme](https://github.com/kadirahq/react-native-storybook/blob/master/readme.md) file and the screenshot in the Readme for more information.

**Comment by elie222** [comment]
The entire storybook is blank for me. And when I start the app, I just see
my regular app running without anything Storybook related.

I've run: npm run storybook

And started my app, but the regular app just starts up.

**Comment by elie222** [comment]
Ah, the issue may be that I'm using Exponent. Someone told me they got it running, but it turns out it wasn't with Exponent in the end.

**Comment by gourav-singhal** [comment]
Hi,

Is this issue resolved ?  I am still getting a blank left story board with no preview.

**Comment by Nasirilahi** [comment]
gourav-singhal You will not be able to see preview in browser as it is mobile app so you will see storied in you simulator/device as you can see in the screenshot and in your browser you will be able to see only actions handlers. Also if you have run command react-native start then you will see only your project running so run npm run storybook command only to see you stories in you simulator/device.

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
